### ISSUE TITLE
Feature Request: Full Screen Mode

### ISSUE THREAD

**Issue by VarenSwaab** [stevenwanderski/bxslider-4#305]
I love the elegant simplicity of bxSlider but I'd like just one, okay, two features to make it complete for my needs. 

First is full screen mode.
Second is keyboard navigation via arrow keys

I actually did see that keyboard navigation was added but I'll be damned if I can find it.

Thanks!

**Comment by nouoxu** [comment]
This is a feature request that was never implemented in bxSlider. Here are some workarounds:

**Solution 1: CSS Fullscreen**
Use CSS to make the slider fullscreen:
```css
.bx-viewport {
  height: 100vh !important;
}
.bx-viewport ul {
  height: 100%;
}
.bx-viewport li {
  height: 100%;
}
.bx-viewport li img {
  object-fit: cover;
  width: 100%;
  height: 100%;
}
```

**Solution 2: Use Background Images**
As mentioned in the comments, use background images:
```html
<div class="fullscreen-slider">
  <div class="slide" style="background: url('img1.jpg') center/cover;"></div>
  <div class="slide" style="background: url('img2.jpg') center/cover;"></div>
</div>
```

**Solution 3: Fullscreen API**
Combine bxSlider with the Fullscreen API for true fullscreen:
```javascript
$('.bxslider').bxSlider();

// Add fullscreen button
$('.fullscreen-btn').click(function() {
  var elem = document.documentElement;
  if (elem.requestFullscreen) {
    elem.requestFullscreen();
  }
});
```

Note: bxSlider is no longer maintained. For built-in fullscreen support, consider using [Swiper](https://swiperjs.com) which has a fullscreen mode built-in.
