### ISSUE TITLE
one group of selectores for controls.png

### ISSUE THREAD

**Issue by szepeviktor** [stevenwanderski/bxslider-4#575]
Would you welcome a PR to group all CSS selectors for controls.png into one?
```css
.bx-wrapper .bx-loading,
.bx-wrapper .bx-prev {
  background-image: url(img/controls.png);
}
```
