### ISSUE TITLE
Slides does not work with Language translation

### ISSUE THREAD

**Issue by arh** [stevenwanderski/bxslider-4#677]
Hello, 

The bxslider is used in our wordpress website for a while. However, it only work in the English page. in the Spanish homepage, For some reason the slider slides are hided. I have manually added following CSS codes to the Spanish homepage and was able to see the slide images. 

```CSS
ul.slides {
height: 400px !important;
}
ul.slides li {
display: block !important;
}
```

However, even with this trick, since the bxSlider does not work, it does not jump into the next slide after a while. 

Would you be able to help me debug the issue here? 
The spanish homepage I am talking about is located at http://parentopia.org/es/
