### ISSUE TITLE
Hide Pager and Navigation if only one page.

### ISSUE THREAD

**Issue by Tidal-Wave** [stevenwanderski/bxslider-4#712]
Was partially addressed in https://github.com/stevenwanderski/bxslider-4/pull/377 but there where issues still and am not sure it needs an option. Will look at making this automatic in update.

**Comment by flowdee** [comment]
For those who can't wait for the update, here's my solution which works like charm :)

```javascript
var oneSlider = ($('#slider').children().length < 2);

$('#slider').bxSlider({
    auto: (!oneSlider),
    pager: (!oneSlider),
});
```

**Comment by xxluke** [comment]
I have an other easy solution with CSS:
```CSS
.bx-pager-item:first-of-type:last-of-type { 
    display: none
}
```
