### ISSUE TITLE
Display all slide images vertically on page load

### ISSUE THREAD

**Issue by ndwl** [stevenwanderski/bxslider-4#893]
How can I stop all the images from displaying when the page with the slider on first loads?

**Comment by davejamesmiller** [comment]
I use this trick to only show the first slide:

```html
<!-- HTML -->
<html lang="en" class="no-js">
```

```js
// JavaScript (or use Modernizr)
$('html').removeClass('no-js').addClass('js');
```

```css
/* CSS */
.no-js .slide {
    display: none;
}

.no-js .slide:first-child {
    display: block;
}
```
